// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG-oGQMF-tQsFtzGmk8IozpQ58tSNHMOg',
    appId: '1:1074232250635:web:9092ae3f4f94a1a9b7120e',
    messagingSenderId: '1074232250635',
    projectId: 'sam-fire-project',
    authDomain: 'sam-fire-project.firebaseapp.com',
    storageBucket: 'sam-fire-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTiKpwRmkVGhQCLlHBQm6YpCv7-D18SJs',
    appId: '1:1074232250635:android:67f120a48676e758b7120e',
    messagingSenderId: '1074232250635',
    projectId: 'sam-fire-project',
    storageBucket: 'sam-fire-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAljjLCx08uoCtXsUU3e89k7kLXAN9oRvE',
    appId: '1:1074232250635:ios:5f44f43a6b6ef3ceb7120e',
    messagingSenderId: '1074232250635',
    projectId: 'sam-fire-project',
    storageBucket: 'sam-fire-project.appspot.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAljjLCx08uoCtXsUU3e89k7kLXAN9oRvE',
    appId: '1:1074232250635:ios:eaf2e67efcd3dd89b7120e',
    messagingSenderId: '1074232250635',
    projectId: 'sam-fire-project',
    storageBucket: 'sam-fire-project.appspot.com',
    iosBundleId: 'com.example.newsapp.RunnerTests',
  );
}
